### ISSUE TITLE
Provide clearer feedback when a package does not explicitly set its default behavior

### ISSUE THREAD

**Issue by alexevanczuk** [rubyatscale/package_protections#3]
Right now when rubocop fails with:
```
All protections must explicitly set unless their default behavior is `fail_never`. Missing protections: prevent_this_package_from_violating_its_stated_dependencies, prevent_other_packages_from_using_this_packages_internals, prevent_this_package_from_exposing_an_untyped_api, prevent_this_package_from_creating_other_namespaces
```

There is no clear indication of which pack is failing. A better output would improve the debuggability of this check.

**Comment by theteep** [comment]
Is there a way to find which pack is missing protections? At the moment I have 8 package.yml files, all of which appear to have the correct protections metadata set, but I'm still seeing this error.

**Comment by AlexEvanczuk** [comment]
@theteep Thanks for sharing this report. Can you share the contents of one of your `package.yml` files? Hopefully I can tell you what's missing and also improve the error message accordingly.

**Comment by AlexEvanczuk** [comment]
Perfect! If you'd like to send a PR to improve this error message I'd love to take a look 😁
